# Generated by Django 2.2.5 on 2019-09-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_mesa', models.IntegerField()),
                ('ativa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemDeComanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Comanda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Produto')),
            ],
        ),
    ]
