# Generated by Django 2.2.5 on 2019-10-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comanda_itemdecomanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
