# Generated by Django 2.2.4 on 2019-09-03 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('schedule', models.DateTimeField(verbose_name='Horário')),
                ('local', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=200)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Commitment')),
            ],
        ),
    ]
