# Generated by Django 2.2.4 on 2019-09-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observations',
            old_name='commitment',
            new_name='fk_commitment',
        ),
    ]
